### ISSUE TITLE
Tighten voter eligibility

### ISSUE THREAD

**Issue by ogiroux** [brycelelbach/wg21_p2195_electronic_straw_polls#1]
There needs to be a way to prevent an onslaught of corporate lobbying, and I don't want to put chairs in an awkward position.

Either use the rules you have with tightening to 1 (or small N) per company, or raise the general bar a bit.

The raised bar I had in mind when I thought about e-voting before:

- Have been at one of the last 3 F2F meetings.
- Are the author of the paper.
- Have had a paper approved by this SG at some time.

**Comment by brycelelbach** [comment]
> Have been at one of the last 3 F2F meetings.

Originally I disliked putting a time limit on this, but someone else also suggested it. Amusingly, they suggested the same period (one of the last three meetings). So, I think I'm on board.

**Comment by brycelelbach** [comment]
A reviewer suggested the "chair's discretion" bullet point for eligibility should be less open-ended:

> the chair has determined that this person has particular expertise in the area of the poll, and this person has participated in on-line discussions preceding the poll

I'm happy to make that change if we keep that bullet point, but I'm also happy to just drop it. However, I do want to note that even if we don't have that bullet point, exceptions to the process should always be allowed when extraordinary circumstances warrant it.

**Comment by brycelelbach** [comment]
A few others have commented on this section; we realized immediately that what we have is a step too far.

Essentially, we were trying to tackle two problems at once:
* Figuring out how to onboard new members without face to face meetings, and
* Propose electronic straw polls.

We still believe that it is important to have a way to onboard new members, but we think that should be separate from this proposal.

My plan is to revise voting eligibility to the following for this proposal:

* The individual is in the ISO global directory (e.g. formal member of a national body), or
* The individual has attended one of the past three face-to-face committee meetings.
