### ISSUE TITLE
Consider making voting results known during voting

### ISSUE THREAD

**Issue by brycelelbach** [brycelelbach/wg21_p2195_electronic_straw_polls#12]
A reviewer pointed out that it may not be a good idea to make voting results hidden until the close of a poll.

They pointed out that the position of another technical expert may sway one's own vote, and that can be a good thing. At face-to-face meetings, we sometimes end up having to revote when one person who voted strongly-against/strongly-for has a particularly good reason. With asynchronous polling, the cost of revoting is high; allowing people to see results before the vote closes would help avoid revotes.

On the other hand, people with strong positions can always share their position on the mailing list ("I'm going to vote X because of Y").

I'm inclined to say that either voting should be anonymous (which I very much do not want to do) or the results should be available during the polling process. The current middleground doesn't seem to make much sense; if the information of who voted how and why is useful after the ballot closes, then it certainly is useful during polling.

**Comment by inbal2l** [comment]
I Support. Reasoning on #11, #4

**Comment by brycelelbach** [comment]
@jfbastien can you comment with your thoughts?

**Comment by brycelelbach** [comment]
One thing to note: INCITS electronic polling system explicitly does not do this.

**Comment by brycelelbach** [comment]
After discussing with @jfbastien, I think we should probably stick with the existing practices of INCITS and ISO. If we allow people to see how others vote during the voting period, it's likely that people will try to interpret and litigate the outcome of the poll prior to the close of the poll. Additionally, some people might be inclined to take a "wait and see" approach of not voting until certain key stakeholders vote. People can always share how they are voting via email during the voting period.
