### ISSUE TITLE
Async polling shouldn't be mandatory for study groups

### ISSUE THREAD

**Issue by hanickadot** [brycelelbach/wg21_p2195_electronic_straw_polls#2]
Study groups are usually small groups with vested people. And making the polls more public can easily swing a decision made by the expert in the area.

**Comment by brycelelbach** [comment]
The proposal as written requires electronic straw polls for decision straw polls for all groups, even at face to face meetings. I'm suggesting we relax this to: 
* Electronic straw polls are required for decision straw polls outside of face to face meetings in Library Evolution/Library/Evolution/Core.
* Electronic straw polls may optionally be used in other circumstances at the discretion of chairs.

See also #6.
