### ISSUE TITLE
Add a process for withdrawing a poll

### ISSUE THREAD

**Issue by brycelelbach** [brycelelbach/wg21_p2195_electronic_straw_polls#20]
A reviewer pointed out that during the duration of a poll, information may come to light that invalidate the poll or require the duration of the poll to be extended. We should document the process for this.

**Comment by inbal2l** [comment]
I agree. this is important. I would suggest something along these lines:


**The Chair can withdraw or extend the duration of a poll under the following circumstances:**

1. New information was received, which may affects the results of the poll, or make them irrelevant.
2. New information was received, which requests further discussion in the group before taking the poll.
3. A specified request by one of the paper's authors.
4. Other circumstances, at his discretion.

The Chair will add a comment, both on the polling system and on "polls@lists.isocpp.org" mailing list, which will describe: 

1. The reason for withdrawing or extending the poll (e.g. Authors have changed direction for this topic, New information reveals this feature is unimplementable) 
and 
2. The action item that will follow. (e.g. The poll will be retaken after a discussion, This poll will not be taken)

If objection to discarding the poll occur [shouldn't be too common, though] and the middle ground is not met, the poll can still be discarded, and the chair will add the topic to the head of next meeting's agenda [naturally]. If needed, a new poll can be created. 

In case of extending the duration of a poll for reasons that aren't technical, the chair will _explicitly_ add a remark requesting from the members who already voted to reconsider their vote after the action item occurs, and will repeat the request after the action item occurred.

Any information described above will be announced at the beginning of the next meeting, and will be added to the notes of the meeting. 

IL

**Comment by brycelelbach** [comment]
Thanks Inbal - I adapted your text, although I shortened it a little as the paper is getting long.
