### ISSUE TITLE
Add rationale for not using secret polling

### ISSUE THREAD

**Issue by ben-craig** [brycelelbach/wg21_p2195_electronic_straw_polls#3]
I agree with the conclusion of the straw poll specification, but I think a section on poll security is needed.  Among those paying attention in the security space, electronic voting for political leaders is a tricky space.  Fortunately, we have things easier.

The proposal is intentionally (and I would say correctly) not using secret ballots.  It allows groups of voters to independently verify the results.  It does leave the process open to intimidation and vote purchasing, but those are already potential issues for the in-person straw polling system we already use.  The electronic aspect does make it logistically easier to distribute the voter roll later.

Recording the votes is largely maintaining the status quo, and avoids exceedingly difficult technical problems and trust problems.

**Comment by jfbastien** [comment]
As in #4, I would stay away from designing process to defend from adversarial behavior. We can create positive process which has upsides and encourages collaboration, good-faith participation, and professionalism. We can create positive processes which provide insight into why people are voting a particular way, and help us understand how to increase consensus.

**Comment by brycelelbach** [comment]
I don't think it hurts for us to add a few sentences on this:

* One stating that open voting allows for verification of the results.
* One stating that recording votes is largely the status quo.
