### ISSUE TITLE
The term "status quo" already has well-defined meaning

### ISSUE THREAD

**Issue by griwes** [brycelelbach/wg21_p2195_electronic_straw_polls#32]
The proposal uses "status quo" to mean the state of papers approved in evolutionary decision polls, which is against the current meaning of the phrase, which is "the state of the working draft after application of all plenary-approved papers". This paper shall not redefine what "status quo" is; rather, a different term should be coined.

**Comment by brycelelbach** [comment]
JF and I discussed this, and tweaked the words a little bit.
