### ISSUE TITLE
Require that voters confirm that they have read the proposal and require voters provide a comment

### ISSUE THREAD

**Issue by inbal2l** [brycelelbach/wg21_p2195_electronic_straw_polls#5]
I suggest adding (the phrasing is only a recommendation):

1.1. Consensus Building Mechanisms

Asynchronous consensus building addresses these shortcomings. It allows more stakeholders to be involved in consensus building, **equalizing the field by removing technical differences**. It removes the pressure and hastiness of trying to determine consensus before the end of a meeting, giving stakeholders more time to contemplate and decide their position.
**All of the above allows including opinions equally in the decision-making process, results in producing a better standard.**  

3.3. Voting

**Each voter will explicitly approve they have read the proposal and are familiar with the topic in hand.** 

(side note: as in face-2-face meetings)

**Comment by inbal2l** [comment]
We've discussed the paper in our NB meeting today.
A point Courtesy of: @regevran, was that adding an obligatory "reasoning comment" (even if short) will help avoiding mass voting by stack holders, as well as verify the paper have been read. (extension to '3.3. Voting')

**Comment by brycelelbach** [comment]
Added the changes suggested in the first comment, with a few editorial changes, please review.

**Comment by brycelelbach** [comment]
I've changed the comment from being optional to being required; what that means is up for discussion, I think. Do we have a minimum comment length, etc?

**Comment by inbal2l** [comment]
Not sure minimum length is needed, I would hope that people will feel obligated to add a decent argument since their name is attached to it. :)
